### PR TITLE
Fix topics filtering by provider

### LINKED ISSUE #136: Topics not filtering by provider for admin
**Describe the bug**
The topics index page is not filtering by provider on load or after changing provider.

**To Reproduce**
1. If you do not have multiple providers who have topics, add them
2. Go to Topics
3. View the list of providers
4. You will see topics from multiple providers
5. Change the provider
6. You will see the same topics

**Expected behavior**
The topics listing should only ever show one provider's topics, even if the user is an admin. Changing the provider should change the available topics.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by Oli0li**
# What Issue Does This PR Cover, If Any?

Resolves #136 

### What Changed? And Why Did It Change?
It redefines the scope of Topics shown on the Topics page to ensure we only display Topics from the currently selected provider.
This fixes a bug that, for Admin users, caused all Topics to be displayed regardless of the Provider, even though the name of the first Provider's was displayed at the top and gave the impression that the Topics were already filtered by Provider.

### How Has This Been Tested?
With system tests (spec/system/topic_search_spec.rb) and by hand

### Please Provide Screenshots

https://github.com/user-attachments/assets/af78f44e-3f07-4a3f-836e-b53b1051019b

### Additional Comments
After making this change, I saw some tests were failing because they are set up in a way where users who are Contributors have no Providers. So I made it so that Contributors can still access the "Topics" page even if they don't have any Providers, in case that's something that may happen when we first add users, but that means they wouldn't be able to see any Topics or create new ones. We could display a message such as "You haven't been added to a provider yet" on the Topics page to clarify the situation, or we could redirect them to the dashboard if they don't have a provider. I wasn't sure what the desired behaviour was, please let me know and I can make the changes.

### CODE REVIEW

**Comment by dmitrytrager** [comment]
@Oli0li please fix conflicts

**Comment by Oli0li** [comment]
> @Oli0li please fix conflicts

Thank you @dmitrytrager! I just resolved the conflict and added a commit to fix a warning I noticed in the tests.

File: app/controllers/topics_controller.rb [hunk 1]
```diff
@@ -89,13 +89,7 @@ def set_topic
...
 
   def scope
-    @scope ||= if Current.user.is_admin?
-      Topic.includes(:provider).all
-    elsif current_provider.present?
-      current_provider.topics
-    else
-      Current.user.topics
-    end.includes(:language)
+    @scope ||= current_provider&.topics&.includes(:language) ||  Topic.none
```
Comment (dmitrytrager) [inline app/controllers/topics_controller.rb:92]: I like the idea of having `Topic.none` here.
What if we also define null object for provider and return it if there is no current provider.
We can define topics association for this null object and will return `Topic.none` there. Using this approach we will have just `current_provider.topics.includes(:language)` without `&`s. Wdyt?

Comment (Oli0li) [reply app/controllers/topics_controller.rb]: Thanks a lot @dmitrytrager! I hadn't used this pattern before, it's very interesting. I added a new commit to add this NullProvider, please let me know what you think.

**Review by dmitrytrager — APPROVED** [review]
LGTM
