### PR TITLE
Fix topics seeds and eager loading

### LINKED ISSUE #143: Fix  seeds and eager loading on topics
**Describe the bug**
- DB seeds are failing.
- Bullet reports an eager loading of providers on topics

**To Reproduce**
Steps to reproduce the behaviour:
1. Run `rails db:prepare` or `rails db:seed`

**Expected behaviour**
- Seeds must work without problem
- Topics UI must run without eager loading providers

####Screenshots**

**Before**
Image

**Before**
Image
Image

### PR DESCRIPTION
**Pull request by hernanvicente**
# What Issue Does This PR Cover, If Any?
- DB seeds are failing
- Bullet reports an eager loading of providers on topics

Resolves #143 

### What Changed? And Why Did It Change?
- The topic seeds were updated
- The topics controller scope includes providers

### Please Provide Screenshots
**Before**
Screenshot 2025-04-12 at 11 48 39

 **After**
Screenshot 2025-04-12 at 11 50 39

**Before**
Screenshot 2025-04-12 at 11 52 21

 **After**
Screenshot 2025-04-12 at 11 53 29

### CODE REVIEW

File: app/controllers/topics_controller.rb [hunk 1]
```diff
@@ -95,7 +95,7 @@ def scope
       current_provider.topics
     else
       Current.user.topics
-    end.includes(:language)
+    end.includes(:language, :provider)
```
Comment (dmitrytrager) [inline app/controllers/topics_controller.rb:98]: 🤔 

While using this branch, I can see the following:
Screenshot 2025-04-12 at 14 35 42

Comment (hernanvicente) [reply app/controllers/topics_controller.rb]: @dmitrytrager Thanks for pointing out my oversight 🙈

**Review by dmitrytrager — APPROVED** [review]
